In [4]:
import pandas as pd 
import numpy as np 
import plotly.express as px
import plotly.graph_objects as go 
import matplotlib.pyplot as plt 
import seaborn as sns

In [5]:
user_data = pd.read_csv('user_data.csv')
typing_data = pd.read_csv('typing_data.csv')
big_data = pd.merge(typing_data, user_data, on='id', how='inner')

In [6]:
medicated = big_data.query("medicated == True")
not_medicated = big_data.query("Parkinsons == True and medicated == False")
control = big_data.query("Parkinsons == False")

med_stats = medicated[['flight_time', 'latency', 'hold_time']].mean()
unmed_stats = not_medicated[['flight_time', 'latency', 'hold_time']].mean()
control_stats = control[['flight_time', 'latency', 'hold_time']].mean()

medicated_dataframe = pd.concat([med_stats, unmed_stats, control_stats], axis=1)
medicated_dataframe.columns = ['Medicated', 'Unmedicated', 'Control']
medicated_dataframe

              Medicated  Unmedicated     Control
flight_time  210.855986   166.401943  176.512399
latency      283.965426   240.504995  250.504971
hold_time    128.344779   103.706316  100.305339

In [7]:
fig = px.bar(medicated_dataframe.T, title='Mean Typing Delay by Medicaiton Status')
fig.update_layout(xaxis_title='Medication Status', yaxis_title='Mean Typing Delay (ms)')
fig.show()

In [8]:
no_impact = big_data.query("Impact == 0")
low = big_data.query("Impact == 1")
medium = big_data.query("Impact == 2")
high = big_data.query("Impact == 3")

no_impact = no_impact[['flight_time', 'latency', 'hold_time']].mean()
low = low[['flight_time', 'latency', 'hold_time']].mean()
medium = medium[['flight_time', 'latency', 'hold_time']].mean()
high = high[['flight_time', 'latency', 'hold_time']].mean()

impact_df = pd.concat([no_impact, low, medium, high], axis=1)
impact_df.columns = ['no impact', 'low impact', 'medium impact', 'high impact']
impact_df

              no impact  low impact  medium impact  high impact
flight_time  176.462496  204.021215     168.909723   261.807586
latency      250.592749  290.070986     228.726707   367.247641
hold_time    102.310082  124.249223     107.908519   133.992147

In [9]:
fig = px.bar(impact_df.T, title='Mean Typing Delay by PD Impact')
fig.update_layout(xaxis_title='Parkinson\'s Impact', yaxis_title='Mean Typing Delay (ms)')
fig.show()

In [10]:
big_data.head()

,id,date,time,hand,hold_time,direction,latency,flight_time,Gender,Parkinsons,Tremors,Sided,UPDRS,Impact,age,medicated
0,NMMGWRY6SO,170301,08:45:42.125,L,187.5,LL,421.9,281.3,Male,True,False,Right,0,1,69.0,False
1,NMMGWRY6SO,170301,08:45:42.422,L,203.1,LL,281.3,93.8,Male,True,False,Right,0,1,69.0,False
2,NMMGWRY6SO,170301,08:48:29.031,L,203.1,LL,296.9,125.0,Male,True,False,Right,0,1,69.0,False
3,NMMGWRY6SO,170301,08:48:29.266,L,218.8,LL,218.8,15.6,Male,True,False,Right,0,1,69.0,False
4,NMMGWRY6SO,170301,08:48:29.484,R,187.5,LR,250.0,31.3,Male,True,False,Right,0,1,69.0,False

In [11]:
no_tremors = big_data.query("Tremors == False")
tremors = big_data.query("Tremors == True")

no_tremors = no_tremors[['flight_time', 'latency', 'hold_time']].mean()
tremors = tremors[['flight_time', 'latency', 'hold_time']].mean()

tremor_df = pd.concat([no_tremors, tremors], axis=1)
tremor_df.columns = ['no tremors', 'tremors']
tremor_df

             no tremors     tremors
flight_time  191.436958  182.907333
latency      271.937259  252.176274
hold_time    111.952746  112.318392

In [12]:
fig = px.bar(tremor_df.T, title='Mean Typing Delay by Tremors')
fig.update_layout(xaxis_title='Tremors', yaxis_title='Mean Typing Delay (ms)')
fig.show()

In [13]:
big_data['time'] = pd.to_datetime(big_data['time'])
big_data['hour'] = big_data['time'].dt.hour

/var/folders/pd/jy2tczp11tvgftzcy6kn7txh0000gn/T/ipykernel_43839/1959279688.py:1: UserWarning:

Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.

In [14]:
big_data

,id,date,time,hand,hold_time,direction,latency,flight_time,Gender,Parkinsons,Tremors,Sided,UPDRS,Impact,age,medicated,hour
0,NMMGWRY6SO,170301,2025-02-25 08:45:42.125,L,187.5,LL,421.9,281.3,Male,True,False,Right,0,1,69.0,False,8
1,NMMGWRY6SO,170301,2025-02-25 08:45:42.422,L,203.1,LL,281.3,93.8,Male,True,False,Right,0,1,69.0,False,8
2,NMMGWRY6SO,170301,2025-02-25 08:48:29.031,L,203.1,LL,296.9,125.0,Male,True,False,Right,0,1,69.0,False,8
3,NMMGWRY6SO,170301,2025-02-25 08:48:29.266,L,218.8,LL,218.8,15.6,Male,True,False,Right,0,1,69.0,False,8
4,NMMGWRY6SO,170301,2025-02-25 08:48:29.484,R,187.5,LR,250.0,31.3,Male,True,False,Right,0,1,69.0,False,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9013559,LSQWWDXEYO,161130,2025-02-25 21:37:08.562,L,187.5,LL,445.3,265.6,Male,True,True,Left,0,1,66.0,False,21
9013560,LSQWWDXEYO,161130,2025-02-25 21:38:03.586,L,179.7,LL,398.4,140.6,Male,True,True,Left,0,1,66.0,False,21
9013561,LSQWWDXEYO,161130,2025-02-25 21:38:03.984,L,187.5,LL,390.6,210.9,Male,True,True,Left,0,1,66.0,False,21
9013562,LSQWWDXEYO,161130,2025-02-25 21:38:04.227,L,171.9,LL,257.8,70.3,Male,True,True,Left,0,1,66.0,False,21
9013563,LSQWWDXEYO,161130,2025-02-25 21:38:04.469,L,125.0,LL,289.1,117.2,Male,True,True,Left,0,1,66.0,False,21

In [15]:

subset = big_data[['flight_time', 'latency', 'hold_time', 'hour', 'medicated', 'Parkinsons','Impact']]

In [16]:
subset['tot_time'] = subset['flight_time'] + subset['latency'] + subset['hold_time']

/var/folders/pd/jy2tczp11tvgftzcy6kn7txh0000gn/T/ipykernel_43839/3832692801.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [17]:
def plot_things(col):
    subset_mean = subset.groupby(['hour',col]).mean().reset_index()
    display(subset_mean)
    fig = px.line(subset_mean, title=f'Mean Total Typing Delay by Hour of Day for Different States of {col}', color=col,x='hour', y='tot_time')
    fig.show()
    return
plot_things('Impact')

,hour,Impact,flight_time,latency,hold_time,medicated,Parkinsons,tot_time
0,0,0,204.306661,282.775103,96.211947,0.087299,0.087299,583.293711
1,0,1,221.756299,312.311991,136.629628,0.732278,0.995698,670.697918
2,0,2,172.300264,248.945931,113.066159,0.319516,1.000000,534.312354
3,0,3,167.865772,279.647648,143.627677,0.996825,1.000000,591.141097
4,1,0,198.551189,277.349157,100.720427,0.085542,0.085542,576.620773
...,...,...,...,...,...,...,...,...
91,22,3,221.983801,316.915983,105.069898,0.959926,1.000000,643.969682
92,23,0,166.804341,245.716072,99.265757,0.060525,0.060525,511.786170
93,23,1,222.688883,311.873247,138.916269,0.782887,0.983089,673.478398
94,23,2,170.322666,235.172122,112.226406,0.419242,1.000000,517.721194
95,23,3,209.112594,327.238053,137.411397,0.759320,1.000000,673.762044

In [18]:
plot_things('medicated')

,hour,medicated,flight_time,latency,hold_time,Parkinsons,Impact,tot_time
0,0,False,181.625475,261.637358,100.487782,0.436745,0.783399,543.750615
1,0,True,227.074506,311.054330,135.701450,1.000000,1.338088,673.830286
2,1,False,180.042999,257.604980,99.435028,0.388371,0.727235,537.083007
3,1,True,229.853606,310.913391,132.564461,1.000000,1.356775,673.331458
4,2,False,166.768115,245.992519,106.600758,0.457801,0.790174,519.361393
5,2,True,206.059343,289.758081,129.689760,1.000000,1.715602,625.507184
6,3,False,157.564040,241.638637,102.680867,0.474395,0.818718,501.883543
7,3,True,210.276373,288.813174,123.409927,1.000000,1.740048,622.499474
8,4,False,160.686178,245.230484,100.108032,0.476292,0.776416,506.024693
9,4,True,209.691090,285.564201,122.826284,1.000000,1.834956,618.081574
10,5,False,168.512981,256.106579,102.479060,0.600323,0.951017,527.098620
11,5,True,213.987714,297.186466,123.010832,1.000000,1.814311,634.185012
12,6,False,173.838852,258.582114,102.959981,0.642187,1.024375,535.380947
13,6,True,215.536790,302.688420,124.911094,1.000000,1.858361,643.136304
14,7,False,180.840701,258.837187,102.411437,0.653088,1.055341,542.089325
15,7,True,211.277534,289.941290,129.138739,1.000000,1.911430,630.357564
16,8,False,174.422693,248.309416,105.076627,0.704569,1.195925,527.808736
17,8,True,219.038065,293.173086,133.229319,1.000000,1.950709,645.440470
18,9,False,174.482993,244.838953,104.082662,0.644798,1.048594,523.404608
19,9,True,211.278487,276.388382,129.186730,1.000000,1.967204,616.853599
20,10,False,172.980093,242.442954,101.250951,0.565960,0.890286,516.673998
21,10,True,215.639944,288.245676,129.431224,1.000000,1.951111,633.316844
22,11,False,175.130258,245.365404,100.261417,0.568518,0.894407,520.757078
23,11,True,219.886570,299.620338,132.222397,1.000000,1.902930,651.729305
24,12,False,179.320958,249.422107,100.325873,0.539528,0.847622,529.068937
25,12,True,197.351688,267.613925,123.747085,1.000000,1.782990,588.712698
26,13,False,172.145939,243.133432,101.755155,0.534393,0.842240,517.034527
27,13,True,220.060986,300.073018,128.694206,1.000000,1.864463,648.828210
28,14,False,173.751134,245.050235,103.177986,0.520746,0.840744,521.979354
29,14,True,225.777587,308.744509,135.953896,1.000000,1.755789,670.475992
30,15,False,176.617371,248.499172,101.783605,0.489104,0.783432,526.900148
31,15,True,218.488211,298.401524,132.446345,1.000000,1.766793,649.336081
32,16,False,168.349276,240.520124,101.146245,0.530348,0.853643,510.015646
33,16,True,207.641272,280.159873,131.563516,1.000000,1.669026,619.364661
34,17,False,169.208209,243.096137,101.370312,0.535162,0.892981,513.674657
35,17,True,200.918086,266.419718,122.523358,1.000000,1.850327,589.861161
36,18,False,165.910319,239.987206,101.016019,0.566895,0.972987,506.913544
37,18,True,201.294263,266.258973,123.881997,1.000000,1.827719,591.435233
38,19,False,165.906658,241.477065,102.005297,0.518503,0.911535,509.389020
39,19,True,199.790311,268.866327,122.508664,1.000000,1.739533,591.165303
40,20,False,163.300087,239.894940,104.885329,0.493678,0.818626,508.080356
41,20,True,199.260622,265.731043,123.508786,1.000000,1.693024,588.500451
42,21,False,159.607748,236.153681,106.103136,0.501436,0.860236,501.864566
43,21,True,201.790384,268.763191,127.222689,1.000000,1.582041,597.776264
44,22,False,155.250540,235.293507,101.970441,0.440918,0.808905,492.514488
45,22,True,214.137919,280.659183,127.034708,1.000000,1.592307,621.831809
46,23,False,162.434854,243.430802,100.927290,0.409077,0.758435,506.792946
47,23,True,215.093964,285.677092,135.910974,1.000000,1.423252,636.682029

In [19]:
plot_things('Parkinsons')

,hour,Parkinsons,flight_time,latency,hold_time,medicated,Impact,tot_time
0,0,False,205.898086,287.183979,95.350165,0.000000,0.002658,588.432230
1,0,True,191.334579,272.701640,122.389489,0.534349,1.548659,586.425707
2,1,False,199.939807,281.866116,100.238598,0.000000,0.000562,582.044521
3,1,True,192.219246,268.469063,116.612436,0.536210,1.595566,577.300745
4,2,False,178.443585,267.175165,111.554867,0.000000,0.000000,557.173617
5,2,True,182.037097,258.620296,116.594698,0.547767,1.720314,557.252091
6,3,False,159.748880,250.436945,104.223459,0.000000,0.000000,514.409284
7,3,True,183.496847,261.164404,112.511131,0.514274,1.733135,557.172382
8,4,False,160.777692,248.458534,98.036165,0.000000,0.000000,507.272391
9,4,True,188.601306,266.717332,114.047683,0.570521,1.746986,569.366322
10,5,False,161.622954,247.275214,97.910313,0.000000,0.000000,506.808481
11,5,True,195.885803,281.602473,115.267570,0.557276,1.712425,592.755846
12,6,False,166.070266,252.020095,97.114984,0.000000,0.000000,515.205345
13,6,True,196.942322,282.561071,115.609043,0.502415,1.727384,595.112436
14,7,False,170.003446,249.621432,100.787178,0.000000,0.000330,520.412055
15,7,True,199.233949,277.151775,116.517235,0.512015,1.767142,592.902959
16,8,False,179.096355,254.526432,102.874189,0.000000,0.010349,536.496977
17,8,True,194.779506,268.448138,119.047036,0.479152,1.816506,582.274680
18,9,False,188.296255,259.576363,104.563974,0.000000,0.012251,552.436591
19,9,True,190.286226,257.635514,117.193508,0.527253,1.802822,565.115249
20,10,False,190.300360,260.882375,103.096039,0.000000,0.034414,554.278774
21,10,True,187.459350,258.049543,114.522938,0.496261,1.747374,560.031831
22,11,False,190.772676,261.375586,98.839836,0.000000,0.047958,550.988099
23,11,True,190.366126,265.002738,116.123514,0.478698,1.712081,571.492378
24,12,False,187.738691,256.497419,98.587248,0.000000,0.064335,542.823358
25,12,True,184.951708,255.698157,112.958977,0.508231,1.651759,553.608843
26,13,False,177.810823,247.915935,98.131114,0.000000,0.052878,523.857872
27,13,True,194.844795,270.917845,117.347568,0.522879,1.704883,583.110208
28,14,False,181.500986,252.263516,100.088223,0.000000,0.069071,533.852725
29,14,True,194.868571,271.997355,120.314996,0.477525,1.648757,587.180922
30,15,False,181.008053,249.186268,99.253580,0.000000,0.080581,529.447901
31,15,True,196.641740,274.597444,119.269948,0.529750,1.649609,590.509132
32,16,False,171.496354,242.049827,99.655939,0.000000,0.060530,513.202119
33,16,True,187.192934,260.238559,117.423506,0.514048,1.614094,564.854998
34,17,False,173.792329,246.376600,99.347708,0.000000,0.069466,519.516638
35,17,True,184.394443,254.302787,113.543761,0.537044,1.738270,552.240991
36,18,False,169.695098,242.702829,98.950158,0.000000,0.060181,511.348085
37,18,True,183.079723,252.769449,113.751621,0.524120,1.752837,549.600793
38,19,False,165.885471,241.750507,101.183404,0.000000,0.026419,508.819382
39,19,True,186.435602,257.964869,114.723880,0.605637,1.737145,559.124351
40,20,False,159.421698,235.498530,102.056695,0.000000,0.021112,496.976922
41,20,True,188.606657,258.626663,118.271422,0.666885,1.674217,565.504742
42,21,False,156.383861,232.447221,103.330949,0.000000,0.019645,492.162031
43,21,True,186.337678,257.296020,119.942491,0.603545,1.627226,563.576190
44,22,False,157.559053,236.501706,100.567103,0.000000,0.036069,494.627862
45,22,True,189.568935,262.019109,117.779854,0.602537,1.670429,569.367897
46,23,False,166.300686,247.278592,98.811072,0.000000,0.010577,512.390350
47,23,True,191.207816,266.072023,122.817528,0.589891,1.593647,580.097368